[View in Colaboratory](https://colab.research.google.com/github/sunnybarnwal/ML_ON1Acadview/blob/master/Assignment_2.ipynb)

In [0]:
import numpy

In [0]:
import numpy as np


In [0]:
x=np.random.randint(10, size=10)

In [10]:
x

array([1, 3, 3, 7, 8, 6, 5, 4, 9, 2])

In [0]:
m=x.mean()

In [12]:
m

4.8

In [0]:
y=np.random.randint(10,size=20)

In [21]:
y

array([2, 4, 9, 7, 2, 7, 1, 7, 6, 7, 1, 7, 9, 2, 0, 7, 1, 0, 5, 7])

In [26]:
y.var()

9.147499999999997

In [27]:
y.std()

3.024483426967322

In [0]:
a=np.random.rand(10,20)

In [37]:
a

array([[0.26684865, 0.87682226, 0.86296947, 0.63764497, 0.42412848,
        0.43857224, 0.44904499, 0.90415664, 0.9072225 , 0.95924157,
        0.22573837, 0.17778974, 0.00552866, 0.76206086, 0.90421606,
        0.55201942, 0.80804085, 0.39480728, 0.19142304, 0.68751145],
       [0.11035413, 0.61581039, 0.40943956, 0.26638632, 0.52999608,
        0.66517866, 0.86217732, 0.40781733, 0.4552717 , 0.08544685,
        0.303202  , 0.02009486, 0.02041274, 0.47479254, 0.0381834 ,
        0.65933241, 0.230718  , 0.71534031, 0.18336305, 0.03230288],
       [0.1685132 , 0.10721281, 0.27683327, 0.54377046, 0.72501248,
        0.19930223, 0.02460327, 0.77417238, 0.55228887, 0.7022371 ,
        0.73442037, 0.35386743, 0.32197124, 0.79473164, 0.90261641,
        0.58453372, 0.53738983, 0.42618594, 0.25198406, 0.37837334],
       [0.40947022, 0.73338242, 0.89844226, 0.68855722, 0.90332512,
        0.88587658, 0.62948169, 0.83663129, 0.79625543, 0.97827404,
        0.87481026, 0.34378457, 0.11916716, 0

In [0]:
b=np.random.rand(20,25)

In [34]:
b

array([[0.78854753, 0.6581677 , 0.73806835, 0.23686077, 0.37619989,
        0.9182275 , 0.08224599, 0.93674442, 0.83537905, 0.49133049,
        0.44981618, 0.0212905 , 0.78237197, 0.93029521, 0.05824712,
        0.33948982, 0.19899526, 0.35954722, 0.28201786, 0.78995091,
        0.67225726, 0.53084157, 0.01359824, 0.66168944, 0.72644179],
       [0.47845301, 0.62197402, 0.26396706, 0.99997859, 0.80109928,
        0.03856463, 0.15641977, 0.76614754, 0.43613982, 0.87499252,
        0.1448486 , 0.98861147, 0.04035723, 0.43839107, 0.45840842,
        0.08638284, 0.31926383, 0.86708711, 0.07861281, 0.95372536,
        0.70163886, 0.23641734, 0.23999235, 0.17031446, 0.47184464],
       [0.99588473, 0.24338518, 0.3508967 , 0.66294581, 0.33969932,
        0.70561168, 0.66746582, 0.07319048, 0.206854  , 0.89548518,
        0.68467352, 0.94282652, 0.44538488, 0.24787019, 0.86874309,
        0.52309031, 0.14127409, 0.69316971, 0.63999133, 0.17291964,
        0.88239915, 0.04155918, 0.92878652, 0.

In [0]:
c=np.dot(a,b)

In [39]:
c

array([[7.77470229, 5.56806049, 4.96841812, 6.05272524, 4.48571264,
        4.6562187 , 5.77781796, 5.64113288, 7.26576604, 5.61258794,
        6.59374894, 7.38851946, 5.21596277, 6.88758555, 7.01709247,
        5.60531076, 6.10178985, 6.3722005 , 5.69982645, 6.21690904,
        7.07659127, 4.83940807, 6.10227683, 7.2991779 , 6.02157341],
       [4.62061558, 3.69571108, 3.01659066, 4.03522868, 3.50190329,
        2.16894652, 3.51721725, 3.98169969, 3.88961881, 3.78767589,
        3.832641  , 4.07940777, 3.16719269, 3.53650742, 4.05392843,
        3.56257944, 3.83876449, 4.05790723, 3.31554476, 3.51764495,
        3.91865154, 3.336624  , 3.94901412, 4.20121247, 3.74956543],
       [6.3793779 , 4.60521481, 4.48876168, 4.49013566, 3.58355753,
        3.80481786, 5.39365399, 4.42969021, 5.76453964, 4.22847366,
        5.760727  , 5.64156197, 4.61027632, 5.59227732, 5.643768  ,
        5.15270072, 5.33252743, 4.86014342, 5.15128337, 4.90745458,
        5.79347535, 4.4624325 , 5.27544825, 5.

In [40]:
np.sum(c)

1263.0485153020845

In [0]:
num=np.random.randint(10,size=10)

In [58]:
num

array([6, 1, 4, 6, 5, 1, 5, 8, 0, 8])

In [0]:
from math import exp
d=[]
def fun(a):
  m=1/(1+exp(-a))
  return m
for i in num:
  b=fun(i)
  d.append(b)

In [59]:
d

[0.9990889488055994,
 0.8807970779778823,
 0.9975273768433653,
 0.5,
 0.9933071490757153,
 0.9996646498695336,
 0.9525741268224334,
 0.9933071490757153,
 0.9820137900379085,
 0.7310585786300049]